#cloud-config
hostname: ${HOSTNAME}
disable_root: false
network:
  config: disabled
users:
  - name: ${USERNAME}
    groups: users, admin, docker, sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_import_id:
      - gh:${GITHUB_USERNAME}
write_files:
- path: /etc/modprobe.d/blacklist.conf
  content: |
    blacklist nouveau
    blacklist lbm-nouveau
- path: /etc/nvidia/gridd.conf
  content: |
    Daemon
    ServerAddress=gridlicense.example.com
    ServerPort=7070
    FeatureType=2
    EnableUI=TRUE
    IgnoreSP=FALSE
    EnableUI=FALSE
package_update: true
package_upgrade: true
packages: 
  - wireguard
  - openresolv
  - ssh-import-id
  - sudo
  - curl
  - tmux
  - netplan.io
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - htop
  - iotop
  - nvtop
  - git-extras
  - rsyslog
  - fail2ban
  - gpg
  - open-iscsi
  - nfs-common
  - ncdu
  - build-essential
  - linux-azure 
  - xubuntu-desktop
  - xrdp
  - xvfb
  - x11vnc
  - xorg
runcmd:
  #####################
  # Import SSH keys
  - sudo -u ${USERNAME} ssh-import-id-gh ${GITHUB_USERNAME}
  ######################
  # Install YQ
  - wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq &&\
  - chmod +x /usr/bin/yq
  ######################
  # Install Docker
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update 
  - sudo apt-get install -y docker-ce
  ########################
  # Install Docker Compose
  - sudo -u ${USERNAME} -i mkdir -p /home/${USERNAME}/.docker/cli-plugins/
  - sudo -u ${USERNAME} -i curl -SL https://github.com/docker/compose/releases/download/v2.17.3/docker-compose-linux-x86_64 -o  /home/${USERNAME}/.docker/cli-plugins/docker-compose
  - sudo chmod +x /home/${USERNAME}/.docker/cli-plugins/docker-compose
  ########################
  # Brew and Python3
  - wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
  - chmod +x /install.sh
  - chmod 777 /install.sh
  - sudo -u friend NONINTERACTIVE=1 /bin/bash /install.sh
  - sudo -u friend /home/linuxbrew/.linuxbrew/bin/brew shellenv >> /home/${USERNAME}/.profile
  - sudo -u friend /home/linuxbrew/.linuxbrew/opt/python@3.11/libexec/bin >> /home/${USERNAME}/.profile
  - sudo -u friend /home/linuxbrew/.linuxbrew/bin/brew install python@3.11 bitwarden-cli b2-tools k9s neovim
  - sudo -u friend /home/linuxbrew/.linuxbrew/bin/pip3.11 install smol-k8s-lab onboardme
  - sudo mkdir -p /home/friend/.config/smol-ka8s-lab
  - sudo chown -R friend:friend /home/linuxbrew
  - sudo chown -R friend:friend /home/friend
  #######################
  # Prometheus
  - wget -O /opt/node_exporter-1.6.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
  - tar -xvf /opt/node_exporter-1.6.1.linux-amd64.tar.gz -C /opt
  - rm /opt/node_exporter-1.6.1.linux-amd64.tar.gz
  - ln -s node_exporter-1.6.1.linux-amd64 /opt/node_exporter
  - wget https://raw.githubusercontent.com/small-hack/smol-metal/main/node-exporter.service
  - sudo mv node-exporter.service /etc/systemd/system/node-exporter.service
  ########################
  # Start system services
  - systemctl daemon-reload
  - systemctl enable node-exporter
  - systemctl restart node-exporter
  - sudo systemctl enable fail2ban
  - sudo systemctl start fail2ban
  - sudo systemctl disable lightdm.service
  #########################
  # Nvidia Driver
  - wget -O NVIDIA-Linux-x86_64-grid.run https://go.microsoft.com/fwlink/?linkid=874272  
  - chmod +x NVIDIA-Linux-x86_64-grid.run
  - sudo ./NVIDIA-Linux-x86_64-grid.run -x
  - sudo bash NVIDIA-Linux-x86_64-grid/nvidia-installer --silent --install-compat32-libs --no-nouveau-check
  - sudo nvidia-xconfig
