name: Run Terraform
on:
  workflow_dispatch:
jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Terraform fmt
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform fmt
      continue-on-error: false
      shell: bash

    - name: Terraform Init
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform init --upgrade
      continue-on-error: false
      shell: bash
      
    - name: Terraform Validate
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform validate --no-color
      continue-on-error: false
      shell: bash
      
    - name: Terraform Plan
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform plan --no-color
      continue-on-error: false
      shell: bash
