name: Run Terraform
on:
  workflow_dispatch:
    inputs:
      vm_sku:
        description: 'Virtual Machine SKU'
        required: true
        default: 'Standard_NV6ads_A10_v5'
      num_instances:
        description: 'Number of Instances'
        required: true
        default: '1'
      max_bid:
        description: 'Maximum spot bid amount'
        required: true
        default: '0.24'        
      allowed_ip:
        description: 'Your IP address'
        required: true
        default: '192.168.50.1' 
      rg_name:
        description: 'Resource Group Name'
        required: true
        default: 'demo-rg'

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Azure CLI
      uses: elstudio/action-install-azure-cli@v1

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Manage Firewalls
      run: |
        chmod +x access-helper.sh && \
        bash -x access-helper.sh "add" "$RUNNER_IP" "$RESOURCE_GROUP" ${{ steps.ip.outputs.rg_name }}
      shell: bash
      env:
        RUNNER_IP: ${{ steps.ip.outputs.ipv4 }}
        RESOURCE_GROUP: ${{ steps.ip.outputs.rg_name }}
        
    - name: Terraform fmt
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform fmt
      continue-on-error: false
      shell: bash

    - name: Terraform Init
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform init --upgrade
      continue-on-error: false
      shell: bash
      
    - name: Terraform Validate
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform validate -no-color
      continue-on-error: false
      shell: bash
      
    - name: Terraform Plan
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform plan -no-color -lock=false -out terraform.plan \
          -var="resource_group=$RESOURCE_GROUP" \
          -var="vm_sku=$VM_SKU" \
          -var="vm_instances=$NUM_INSTANCES" \
          -var="max_bid_price=$MAX_BID" \
          -var='allowed_ips=["${{github.event.inputs.allowed_ip}}", "${{ steps.ip.outputs.ipv4 }}"]'
      continue-on-error: false
      shell: bash
      env:
        VM_SKU: ${{github.event.inputs.vm_sku}}
        DISK_SIZE: 64
        NUM_INSTANCES: ${{github.event.inputs.num_instances}}
        MAX_BID: ${{github.event.inputs.max_bid}}
        ALLOWED_IPS: ${{github.event.inputs.allowed_ip}}
        RUNNER_IP: ${{ steps.ip.outputs.ipv4 }}
        RESOURCE_GROUP: ${{ steps.ip.outputs.rg_name }}

    - name: Terraform Apply
      id: apply
      run: |
        docker run --platform linux/amd64 \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -v $(pwd):/terraform -w /terraform \
          hashicorp/terraform apply -no-color -auto-approve -input=false \
          -var="resource_group=$RESOURCE_GROUP" \
          -var="vm_sku=$VM_SKU" \
          -var="vm_instances=$NUM_INSTANCES" \
          -var="max_bid_price=$MAX_BID" \
          -var='allowed_ips=["${{github.event.inputs.allowed_ip}}", "${{ steps.ip.outputs.ipv4 }}"]'
      continue-on-error: false
      shell: bash
      env:
        VM_SKU: ${{github.event.inputs.vm_sku}}
        DISK_SIZE: 64
        NUM_INSTANCES: ${{github.event.inputs.num_instances}}
        MAX_BID: ${{github.event.inputs.max_bid}}
        ALLOWED_IPS: ${{github.event.inputs.allowed_ip}}
        RUNNER_IP: ${{ steps.ip.outputs.ipv4 }}
        RESOURCE_GROUP: ${{ steps.ip.outputs.rg_name }}
